import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { Toaster } from "sonner";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || '/';

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  // Define route requirements
  const guestOnlyRoutes = ['/', '/login', '/signup'];
  const customerOnlyRoutes = ['/account', '/booking', '/settings'];
  const businessOnlyRoutes = ['/admin', '/onboarding'];
  const customerOrGuestRoutes = ['/search', '/ticket'];

  if (!user) {
    if (
      customerOnlyRoutes.some(route => pathname.startsWith(route)) ||
      businessOnlyRoutes.some(route => pathname.startsWith(route))
    ) {
      redirect('/login');
    }
  } else {
    // Get custom claims from the session token
    const { data: { session } } = await supabase.auth.getSession();
    const rawRole = session?.user?.app_metadata?.role as string;
    const userRole = (rawRole === 'business' || rawRole === 'customer') ? rawRole : 'customer';
    const onboardingStep = (session?.user?.app_metadata?.onboarding_step as number) || 0;
    const isUnonboardedBusiness = userRole === 'business' && onboardingStep < 3;

    let homeRoute = userRole === 'business' ? '/admin' : '/search';
    if (isUnonboardedBusiness) {
      homeRoute = '/onboarding';
    }

    if (guestOnlyRoutes.includes(pathname)) {
      redirect(homeRoute);
    }

    if (isUnonboardedBusiness && !pathname.startsWith('/onboarding')) {
      redirect('/onboarding');
    }

    if (userRole === 'customer' && businessOnlyRoutes.some(route => pathname.startsWith(route))) {
      redirect(homeRoute);
    }

    if (userRole === 'business' && (
      customerOnlyRoutes.some(route => pathname.startsWith(route)) ||
      customerOrGuestRoutes.some(route => pathname.startsWith(route))
    )) {
      redirect(homeRoute);
    }
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
